### ISSUE TITLE
Please update Platform script

### ISSUE THREAD

**Issue by BestNoob** [maniaplanet/game-modes#5]
A lot TitlePacks have Platform or other old script modes integrated. But most creators are not aware of the changes you from nadeo made, and also not that they have to EDIT and update this scripts !

Would be cool when you update platform@nadeolive and the script for platform

Related with: https://forum.maniaplanet.com/viewtopic.php?f=527&t=46344
and https://forum.maniaplanet.com/viewtopic.php?f=659&t=45303

**Comment by Aessi** [comment]
[see](https://github.com/maniaplanet/game-modes/issues/4).
